### ISSUE TITLE
ResourceAttributes look wrong for authorization

### ISSUE THREAD

**Issue by waynr** [kontena/kubelet-rubber-stamp#10] opened 2019-08-21 15:26 UTC
While evaluating `kubelet-rubber-stamp` for use on my team's product I noticed the following:

* https://github.com/kontena/kubelet-rubber-stamp/blob/602e5db20e5d251fbc8e4d4dfcff0aeb34cc9b46/pkg/controller/certificatesigningrequest/certificatesigningrequest_controller.go#L33

This looks wrong to me since it seems to be rubber stamping if the service account has permission to create `certificatesigningrequests` rather than `certificatesigningrequests/approval` -- we implicitly know that the service account has permission to create `certificatesigningrequests` based on the fact that the CSR exists in the first place, what we should really care about when auto-approving is whether the service account has permission to approve CSRs.

I guess the problem may be that the `system:node` cluster role doesn't have any `certificatesigningrequests/approval` permissions (at least not be default in my cluster) so maybe there's nothing to do here, but I thought I'd see what y'all think.

**Comment by jnummelin** [comment] 2019-08-22 05:44
As the repo name suggests, it is sort of a "rubber stamper". :D The logic, and bit's of code, are borrowed from kube core for automated approval for kubelet client certs, see https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/certificates/approver/sarapprove.go

By design the `CSRApprovingController` will not handle kubelet serving certs, so we adapted the same logic to serving certs for kubelet.

You are correct in the sense that it is merely a rubber stamp, we really do not have any better ways to validate the CSRs. Currently the verification only kinda checks that we cannot get a serving certificate for a node not existing in the cluster as it uses the node identity in the subject access review.

IMO using `certificatesigningrequests/approval` would be slightly "wrong" as it's not the node itself actually approving the CSR. And with quick thinking it would not improve the situation at all. You'd still end up having rubber stamping in place as all the nodes will (need to) have the permissions to `certificatesigningrequests/approval`. I _think_ it might be possible to require this "elevated" permission and then bind it only on specific nodes by administrative process (manual or automated). But that makes cases such as autoscaling PITA. I guess this boils down to thinking like: "If a node is able to authenticate and authorize on API, we need to trust it anyway. Why not trust it enough to give a **serving** cert for it as kube core has already approved a client cert too for it."

And yes, part of the problem is the fact that by default `system:node` role does not have any "elevated" permissions on CSRs. So we wanted `kubelet-rubber-stamp` to have the least changes needed to "standard" node permissions for it to be applicable on any cluster.

**Comment by waynr** [comment] 2019-08-23 23:12
Hey @jnummelin thanks for the quick response! You make a bunch of great points that I hadn't really thought about, thanks too for that.

I think I filed this issue while kind of blindly stumbling my way through writing some e2e test cases around `kubelet-rubber-stamp` to develop a better practical understanding of the security implications of deploying it in the product my team supports. Here's a rough outline of how my test cases work:

* For various service accounts in a cluster:
  * obtain a [service account token](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#service-account-tokens)
  * construct a client set [using bearer token auth with the service account token](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#putting-a-bearer-token-in-a-request)
  * craft a CSR that [looks exactly like the kubelet's CSR](https://github.com/kontena/kubelet-rubber-stamp/blob/602e5db20e5d251fbc8e4d4dfcff0aeb34cc9b46/pkg/controller/certificatesigningrequest/helpers.go#L71-L88)

Regardless of which service account I use for this purpose, even the `default` service account in the `default` namespace, I am able to get the CSR approved. This violated my intuition, so I reached out and filed this ticket mistakenly thinking it was a problem of incorrect RBAC permissions since it seems tautological to validate that the account which created the CSR has the permissions to create CSRs.

However, taking a closer look at the built-in client cert approver that you linked I see one major difference which is that [the CSR spec username is in some cases checked against the CommonName of the CSR itself](https://github.com/kubernetes/kubernetes/blob/220498b83af8b5cbf8c1c1a012b64c956d3ebf9b/pkg/controller/certificates/approver/sarapprove.go#L191).

It seems to me like using information that we can be reasonably certain about at this point in the lifecycle of the cluster (the kubelet is presumably authenticated with the apiserver using its client cert) such as the name of the account that created the CSR is probably a good idea to prevent auto-approving arbitrary Kubelet serving certificates to any service account that has the permission to create a CSR. In fact, this is exactly how Kubernetes itself [did it in the past](https://github.com/kubernetes/kubernetes/commit/7665f15b7d8d9006e410e41f6678cfa2be3ac602#diff-05476437bf221fbe4cab028bf7ffbb74L224).

What would you think if I submitted a PR to add this restriction to kubelet-rubber-stamp?

**Comment by waynr** [comment] 2019-08-23 23:31
Another difference I noticed with the client cert auto approver is that they do actually [rely on a different resource permission than what I see in `kubelet-rubber-stamp`](https://github.com/kubernetes/kubernetes/blob/220498b83af8b5cbf8c1c1a012b64c956d3ebf9b/pkg/controller/certificates/approver/sarapprove.go#L59-L70). Specifically, they match against the `nodeclient` or `selfnodeclient` subresources of the `certificatesigningrequests` resource.

I see the PR that I mentioned in my previous comment removing auto-approving server cert rotation also removed a `selfnodeserver` subresource from `certificatesigningrequests` so that wouldn't be an option for `kubelet-rubber-stamp`, but what do you think about piggybacking off of `selfnodeclient`?

**Comment by jnummelin** [comment] 2019-08-26 09:48
I think just validating better the source being really kubelet might be enough. With a quick testing API seems to always put the user info (coming from auth layers) properly into the CSR details. We already verify that it's a serving cert we're approving, so limiting those to be coming from kubelet should be enough IMO.

**Comment by waynr** [comment] 2019-08-26 14:01
Okay I'll submit the PR today after I get a chance to validate it works as expected in my e2e test cases.

**Comment by waynr** [comment] 2019-09-01 11:33
By the way, I found a bug in some of my test code around building a clientset for service accounts which gave that test code the appearance of allowing arbitrary service accounts to create CSRs, but it was actually still authenticated using the admin kubeconfig -- I had been confused about how the clientset overrides work.

But I think this issue and the related PR are still valid in terms of preventing arbitrary service accounts with permission to create CSRs from getting a kubelet-like CSR auto-approved.

**Comment by jnummelin** [comment] 2019-09-06 12:02
fixed in #11

**Closed as completed by jnummelin** 2019-09-06 12:02 UTC
